backend_user_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Backend/User:index" }

backend_user_show:
    path:     /{id}/show
    defaults: { _controller: "SiteMainBundle:Backend/User:show" }

backend_user_new:
    path:     /new
    defaults: { _controller: "SiteMainBundle:Backend/User:new" }

backend_user_create:
    path:     /create
    defaults: { _controller: "SiteMainBundle:Backend/User:create" }
    methods:  POST

backend_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteMainBundle:Backend/User:edit" }

backend_user_change_password:
    path:     /{id}/change-password
    defaults: { _controller: "SiteMainBundle:Backend/User:changePassword" }

backend_user_update:
    path:     /{id}/update
    defaults: { _controller: "SiteMainBundle:Backend/User:update" }
    methods:  [POST, PUT]

backend_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteMainBundle:Backend/User:delete" }
    methods:  [POST, DELETE]
