frontend_ajax_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/News:ajax" }

frontend_news_index:
    path:     /{type}
    defaults: { _controller: "SiteMainBundle:Frontend/News:index" }
    requirements:
      type: all|official|quickly|meeting|point_view|analytics

frontend_news_one:
    path:     /{type}/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/News:one" }
    requirements:
      type: all|official|quickly|meeting|point_view|analytics