frontend_news_paper_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/NewsPaper:index" }

frontend_news_paper_one:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/NewsPaper:one" }