frontend_quote_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Quote:index" }

frontend_quote_main:
    path:     /main
    defaults: { _controller: "SiteMainBundle:Frontend/Quote:main" }

frontend_quote_one:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Quote:one" }