frontend_video_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Video:index" }

frontend_video_one:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Video:one" }