<?php

namespace Site\MainBundle\Entity\Repository;

/**
 * NewsPaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPaperRepository extends \Doctrine\ORM\EntityRepository
{
}
