<?php

namespace Site\MainBundle\Entity\Repository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        return $this->createQueryBuilder('q')
            ->orderBy('q.date', 'desc')
            ->getQuery()
            ->getResult();
    }

    //  Три последних цитаты
    public function findLast(){

        $em = $this->getEntityManager();

        $quotes = $em->createQuery('
        SELECT q FROM Site\MainBundle\Entity\Quote q
        ORDER BY q.date DESC
        ')
            ->setMaxResults(3)
            ->getResult();

        return $quotes;

    }
}
